/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FreeQPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  serverUrl: "wss://irc.freeq.at/irc",
  brokerUrl: "https://auth.freeq.at",
  callbackUrl: "https://codegod100.github.io/freeq-obsidian/oauth-callback.html",
  nick: "",
  did: "",
  lastHandle: "",
  appPassword: "",
  pdsUrl: "https://bsky.social",
  autoJoinChannels: "#general",
  lastChannel: "",
  clipFolder: "FreeQ Clippings",
  clipTemplate: `> {{text}}
> \u2014 @{{from}} in {{channel}}, {{timestamp}}
> [msgid: {{msgid}}]`,
  useDailyNote: false,
  dailyNoteFormat: "YYYY-MM-DD"
};
var FreeQSettingTab = class extends import_obsidian.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", { text: "Authentication" });
    if (this.plugin.settings.oauthSession) {
      const displayName = this.plugin.settings.oauthSession.handle || this.plugin.settings.oauthSession.did;
      new import_obsidian.Setting(containerEl).setName("Logged in as @" + displayName).setDesc(this.plugin.settings.oauthSession.did).addButton(
        (button) => button.setButtonText("Log out").setWarning().onClick(async () => {
          this.plugin.settings.oauthSession = void 0;
          this.plugin.settings.did = "";
          await this.plugin.saveSettings();
          this.display();
          new import_obsidian.Notice("Logged out successfully");
        })
      );
    } else {
      {
        let handleInput;
        new import_obsidian.Setting(containerEl).setName("Log in with AT Protocol").setDesc("Enter your handle (e.g., alice.bsky.social) to authenticate via Bluesky.").addText((text) => {
          handleInput = text.inputEl;
          text.setPlaceholder("alice.bsky.social");
        }).addButton(
          (button) => button.setButtonText("Log in").setCta().onClick(async () => {
            const handle = handleInput.value.trim();
            if (!handle) {
              new import_obsidian.Notice("Please enter a handle.");
              return;
            }
            try {
              button.setDisabled(true);
              button.setButtonText("Logging in\u2026");
              await this.plugin.initiateOAuth(handle);
              this.display();
              new import_obsidian.Notice(`Logged in as ${this.plugin.settings.oauthSession?.handle || handle}`);
            } catch (e) {
              console.error("[freeq] OAuth login failed:", e);
              new import_obsidian.Notice(`Login failed: ${e.message || String(e)}`);
            } finally {
              button.setDisabled(false);
              button.setButtonText("Log in");
            }
          })
        );
        containerEl.createEl("p", {
          cls: "setting-item-description",
          text: "A browser window will open to complete authorization. Return to Obsidian when done."
        });
      }
      containerEl.createEl("h3", { text: "Fallback: App Password" });
      containerEl.createEl("p", {
        cls: "setting-item-description",
        text: "If OAuth doesn't work for your setup, use an app password instead."
      });
      new import_obsidian.Setting(containerEl).setName("DID or Handle").setDesc("Required for authenticated login.").addText(
        (text) => text.setPlaceholder("alice.bsky.social").setValue(this.plugin.settings.did).onChange(async (value) => {
          this.plugin.settings.did = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("App Password").setDesc("An app password from your PDS. Stored locally.").addText((text) => {
        text.inputEl.type = "password";
        text.setPlaceholder("xxxx-xxxx-xxxx-xxxx").setValue(this.plugin.settings.appPassword).onChange(async (value) => {
          this.plugin.settings.appPassword = value;
          await this.plugin.saveSettings();
        });
      });
    }
    containerEl.createEl("h3", { text: "Server & Identity" });
    new import_obsidian.Setting(containerEl).setName("Server URL").setDesc("WebSocket URL of the FreeQ IRC server").addText(
      (text) => text.setPlaceholder("wss://irc.freeq.at/irc").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
        this.plugin.settings.serverUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Broker URL").setDesc("FreeQ auth broker (for OAuth and session refresh)").addText(
      (text) => text.setPlaceholder("https://auth.freeq.at").setValue(this.plugin.settings.brokerUrl).onChange(async (value) => {
        this.plugin.settings.brokerUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("OAuth callback URL").setDesc("The page that redirects back to Obsidian after browser auth. Host oauth-callback.html from this plugin's directory.").addText(
      (text) => text.setPlaceholder("https://yourdomain.com/oauth-callback.html").setValue(this.plugin.settings.callbackUrl).onChange(async (value) => {
        this.plugin.settings.callbackUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Nick override").setDesc("Custom IRC nick. Leave blank to derive from handle.").addText(
      (text) => text.setPlaceholder("mynick").setValue(this.plugin.settings.nick).onChange(async (value) => {
        this.plugin.settings.nick = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("PDS URL").setDesc("Your AT Protocol PDS. Only needed for app-password fallback.").addText(
      (text) => text.setPlaceholder("https://bsky.social").setValue(this.plugin.settings.pdsUrl).onChange(async (value) => {
        this.plugin.settings.pdsUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-join channels").setDesc("Comma-separated list of channels to join on connect.").addText(
      (text) => text.setPlaceholder("#general, #random").setValue(this.plugin.settings.autoJoinChannels).onChange(async (value) => {
        this.plugin.settings.autoJoinChannels = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Clipping" });
    new import_obsidian.Setting(containerEl).setName("Use daily note").setDesc("Append clippings to today's daily note instead of a dedicated folder.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useDailyNote).onChange(async (value) => {
        this.plugin.settings.useDailyNote = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (!this.plugin.settings.useDailyNote) {
      new import_obsidian.Setting(containerEl).setName("Clippings folder").setDesc("Folder where clipped messages are saved.").addText(
        (text) => text.setPlaceholder("FreeQ Clippings").setValue(this.plugin.settings.clipFolder).onChange(async (value) => {
          this.plugin.settings.clipFolder = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Clip template").setDesc("Available variables: {{text}}, {{from}}, {{channel}}, {{timestamp}}, {{msgid}}, {{url}}").addTextArea((text) => {
      text.setPlaceholder(DEFAULT_SETTINGS.clipTemplate).setValue(this.plugin.settings.clipTemplate).onChange(async (value) => {
        this.plugin.settings.clipTemplate = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 6;
      text.inputEl.cols = 40;
    });
    containerEl.createEl("h3", { text: "Actions" });
    const actionDiv = containerEl.createDiv();
    const connectBtn = actionDiv.createEl("button", { text: "Connect" });
    connectBtn.addClass("mod-cta");
    connectBtn.style.marginRight = "8px";
    connectBtn.addEventListener("click", () => {
      this.plugin.connect();
    });
    const disconnectBtn = actionDiv.createEl("button", { text: "Disconnect" });
    disconnectBtn.addEventListener("click", () => {
      this.plugin.disconnect();
    });
  }
};

// src/irc/parser.ts
function prefixNick(prefix) {
  const i = prefix.indexOf("!");
  return i > 0 ? prefix.slice(0, i) : prefix;
}
function parse(raw) {
  let line = raw.replace(/\r?\n$/, "");
  const tags = {};
  if (line.startsWith("@")) {
    const sp = line.indexOf(" ");
    const tagStr = line.substring(1, sp);
    line = line.slice(sp + 1).trimStart();
    for (const t of tagStr.split(";")) {
      const eq = t.indexOf("=");
      if (eq >= 0) {
        tags[t.slice(0, eq)] = t.slice(eq + 1).replace(/\\s/g, " ").replace(/\\:/g, ";").replace(/\\\\/g, "\\").replace(/\\r/g, "\r").replace(/\\n/g, "\n");
      } else {
        tags[t] = "";
      }
    }
  }
  let prefix = "";
  if (line.startsWith(":")) {
    const sp = line.indexOf(" ");
    prefix = line.slice(1, sp);
    line = line.slice(sp + 1);
  }
  const params = [];
  while (line.length) {
    if (line.startsWith(":")) {
      params.push(line.slice(1));
      break;
    }
    const sp = line.indexOf(" ");
    if (sp < 0) {
      params.push(line);
      break;
    }
    params.push(line.slice(0, sp));
    line = line.slice(sp + 1);
  }
  const command = (params.shift() || "").toUpperCase();
  return { tags, prefix, command, params };
}
function serializeTags(tags) {
  return Object.entries(tags).map(([k, v]) => {
    const escaped = v.replace(/\\/g, "\\\\").replace(/;/g, "\\:").replace(/ /g, "\\s").replace(/\r/g, "\\r").replace(/\n/g, "\\n");
    return escaped ? `${k}=${escaped}` : k;
  }).join(";");
}
function format(command, params, tags) {
  let line = "";
  if (tags && Object.keys(tags).length > 0) {
    line += `@${serializeTags(tags)} `;
  }
  line += command;
  for (let i = 0; i < params.length; i++) {
    if (i === params.length - 1 && (params[i].includes(" ") || params[i].startsWith(":"))) {
      line += ` :${params[i]}`;
    } else {
      line += ` ${params[i]}`;
    }
  }
  return line;
}

// src/irc/transport.ts
var Transport = class _Transport {
  ws = null;
  opts;
  reconnectTimer = null;
  reconnectAttempts = 0;
  intentionalClose = false;
  lastDataReceived = 0;
  heartbeatTimer = null;
  // If no data received in 45s, send a client-side PING.
  // If no data received in 90s, assume connection is dead and force reconnect.
  static PING_INTERVAL = 45e3;
  static DEAD_TIMEOUT = 9e4;
  constructor(opts) {
    this.opts = opts;
  }
  connect() {
    this.intentionalClose = false;
    this.opts.onStateChange("connecting");
    try {
      this.ws = new WebSocket(this.opts.url);
    } catch {
      this.opts.onStateChange("disconnected");
      this.scheduleReconnect();
      return;
    }
    this.ws.onopen = () => {
      this.reconnectAttempts = 0;
      this.lastDataReceived = Date.now();
      this.opts.onStateChange("connected");
      this.startHeartbeat();
    };
    this.ws.onmessage = (e) => {
      this.lastDataReceived = Date.now();
      const data = typeof e.data === "string" ? e.data : "";
      for (const line of data.split("\n")) {
        const trimmed = line.replace(/\r$/, "");
        if (trimmed) {
          this.opts.onLine(trimmed);
        }
      }
    };
    this.ws.onclose = () => {
      this.stopHeartbeat();
      this.opts.onStateChange("disconnected");
      if (!this.intentionalClose) {
        this.scheduleReconnect();
      }
    };
    this.ws.onerror = () => {
    };
  }
  send(line) {
    if (this.ws?.readyState === WebSocket.OPEN) {
      if (this.ws.bufferedAmount > 65536) {
        console.warn("[transport] High bufferedAmount, forcing reconnect");
        this.ws.close();
        return;
      }
      this.ws.send(line);
    } else {
      console.warn("[transport] Dropped message (ws not open, readyState=%s):", this.ws?.readyState, line);
    }
  }
  disconnect() {
    this.intentionalClose = true;
    this.stopHeartbeat();
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
    if (this.ws) {
      try {
        this.send("QUIT :Leaving");
      } catch {
      }
      this.ws.close();
      this.ws = null;
    }
    this.opts.onStateChange("disconnected");
  }
  startHeartbeat() {
    this.stopHeartbeat();
    this.heartbeatTimer = setInterval(() => {
      const elapsed = Date.now() - this.lastDataReceived;
      if (elapsed > _Transport.DEAD_TIMEOUT) {
        console.warn("[transport] No data for 90s, forcing reconnect");
        this.stopHeartbeat();
        if (this.ws) {
          this.ws.close();
          this.ws = null;
        }
      } else if (elapsed > _Transport.PING_INTERVAL) {
        this.send("PING :heartbeat");
      }
    }, 15e3);
  }
  stopHeartbeat() {
    if (this.heartbeatTimer) {
      clearInterval(this.heartbeatTimer);
      this.heartbeatTimer = null;
    }
  }
  scheduleReconnect() {
    if (this.reconnectTimer || this.intentionalClose) return;
    this.reconnectAttempts++;
    const delay = Math.min(1e3 * Math.pow(2, this.reconnectAttempts - 1), 3e4);
    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      this.connect();
    }, delay);
  }
};

// src/irc/client.ts
var IRCClient = class {
  transport = null;
  nick = "";
  desiredNick = "";
  url = "";
  ackedCaps = /* @__PURE__ */ new Set();
  registered = false;
  authenticatedDid = "";
  // SASL credentials
  saslToken = "";
  saslDid = "";
  saslMethod = "";
  // Channels
  channels = /* @__PURE__ */ new Map();
  _activeChannel = "";
  onActiveChannelChange = null;
  get activeChannel() {
    return this._activeChannel;
  }
  set activeChannel(channel) {
    const next = channel.trim();
    if (next === this._activeChannel) return;
    this._activeChannel = next;
    this.onActiveChannelChange?.(next);
  }
  serverMessages = [];
  // Batches (CHATHISTORY)
  batches = /* @__PURE__ */ new Map();
  // Callbacks
  listeners = [];
  // Pending WHOIS (background)
  backgroundWhois = /* @__PURE__ */ new Set();
  // Message ID counter for local echo
  localIdSeq = 0;
  connect(url, desiredNick, saslToken, saslDid, saslMethod) {
    this.disconnect();
    this.url = url;
    this.desiredNick = desiredNick;
    this.nick = desiredNick;
    this.saslToken = saslToken || "";
    this.saslDid = saslDid || "";
    this.saslMethod = saslMethod || "";
    this.registered = false;
    this.authenticatedDid = "";
    this.ackedCaps = /* @__PURE__ */ new Set();
    this.channels.clear();
    this.serverMessages = [];
    this.batches.clear();
    let lineQueue = Promise.resolve();
    const serializedHandleLine = (line) => {
      lineQueue = lineQueue.then(() => this.handleLine(line)).catch((e) => console.error("[irc] line handler error:", e));
    };
    this.transport = new Transport({
      url,
      onLine: serializedHandleLine,
      onStateChange: (s) => {
        this.emit({ type: "state", state: s });
        if (s === "connected") {
          this.sendRegistration();
        }
      }
    });
    this.transport.connect();
  }
  disconnect() {
    this.transport?.disconnect();
    this.transport = null;
  }
  isConnected() {
    return this.registered && this.transport !== null;
  }
  get currentNick() {
    return this.nick;
  }
  addListener(fn) {
    this.listeners.push(fn);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== fn);
    };
  }
  /** Returns a promise that resolves when the server sends 001 (registered).
   *  Rejects after timeoutMs if registration never completes. */
  waitForRegistration(timeoutMs = 3e4) {
    if (this.registered) return Promise.resolve(this.nick);
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        remove();
        reject(new Error("Registration timed out"));
      }, timeoutMs);
      const remove = this.addListener((ev) => {
        if (ev.type === "registered") {
          clearTimeout(timer);
          remove();
          resolve(ev.nick);
        } else if (ev.type === "state" && ev.state === "disconnected") {
          clearTimeout(timer);
          remove();
          reject(new Error("Disconnected during registration"));
        }
      });
    });
  }
  emit(ev) {
    for (const fn of this.listeners) {
      try {
        fn(ev);
      } catch (e) {
        console.error("[irc] event handler error:", e);
      }
    }
  }
  sendRegistration() {
    this.ackedCaps = /* @__PURE__ */ new Set();
    this.raw("CAP LS 302");
    this.raw(`NICK ${this.desiredNick}`);
    this.raw(`USER ${this.desiredNick} 0 * :FreeQ Obsidian`);
  }
  // ── Sending ──
  raw(line) {
    this.transport?.send(line + "\r\n");
  }
  sendPrivmsg(target, text, replyTo) {
    const tags = replyTo ? { "+reply": replyTo } : {};
    this.raw(format("PRIVMSG", [target, text], tags));
    if (!this.ackedCaps.has("echo-message")) {
      this.addMessage(target, {
        id: this.nextLocalId(),
        from: this.nick,
        text,
        timestamp: /* @__PURE__ */ new Date(),
        tags,
        isSelf: true,
        replyTo
      });
    }
  }
  sendAction(target, text) {
    this.raw(`PRIVMSG ${target} :ACTION ${text}`);
  }
  join(channel) {
    this.raw(`JOIN ${channel}`);
    this.ensureChannel(channel);
    this.activeChannel = channel;
  }
  part(channel) {
    this.raw(`PART ${channel}`);
    const ch = this.channels.get(channel.toLowerCase());
    if (ch) {
      ch.isJoined = false;
      this.emit({ type: "channelUpdated", channel: ch.name });
    }
  }
  requestHistoryLatest(target, count = 50) {
    this.raw(`CHATHISTORY LATEST ${target} * ${count}`);
  }
  requestHistoryBefore(target, msgid, count = 50) {
    this.raw(`CHATHISTORY BEFORE ${target} msgid=${msgid} ${count}`);
  }
  whois(nick) {
    this.backgroundWhois.add(nick.toLowerCase());
    this.raw(`WHOIS ${nick}`);
  }
  // ── Helpers ──
  nextLocalId() {
    return `local-${++this.localIdSeq}`;
  }
  ensureChannel(name) {
    const key = name.toLowerCase();
    let ch = this.channels.get(key);
    if (!ch) {
      ch = {
        name,
        topic: "",
        members: /* @__PURE__ */ new Map(),
        messages: [],
        modes: /* @__PURE__ */ new Set(),
        isJoined: false,
        unreadCount: 0
      };
      this.channels.set(key, ch);
    }
    return ch;
  }
  addMessage(target, msg) {
    const ch = this.ensureChannel(target);
    if (msg.editOf) {
      const existing = ch.messages.find((m) => m.id === msg.editOf);
      if (existing) {
        existing.text = msg.text;
        this.emit({ type: "channelUpdated", channel: ch.name });
        return;
      }
    }
    ch.messages.push(msg);
    if (ch.messages.length > 500) {
      ch.messages.splice(0, ch.messages.length - 500);
    }
    if (ch.name.toLowerCase() !== this.activeChannel.toLowerCase()) {
      ch.unreadCount++;
    }
    this.emit({ type: "message", channel: ch.name, msg });
    this.emit({ type: "channelUpdated", channel: ch.name });
  }
  addServerMessage(text, isSystem = true) {
    const msg = {
      id: this.nextLocalId(),
      from: "",
      text,
      timestamp: /* @__PURE__ */ new Date(),
      tags: {},
      isSystem
    };
    this.serverMessages.push(msg);
    if (this.serverMessages.length > 200) {
      this.serverMessages.shift();
    }
    this.emit({ type: "serverMessage", msg });
  }
  // ── Receiving ──
  async handleLine(line) {
    const m = parse(line);
    switch (m.command) {
      case "PING": {
        const payload = m.params[0] || "";
        this.raw(`PONG :${payload}`);
        break;
      }
      case "CAP": {
        const sub = m.params[1]?.toUpperCase();
        if (sub === "LS") {
          const caps = m.params[2] || "";
          const want = [
            "message-tags",
            "server-time",
            "batch",
            "echo-message",
            "away-notify",
            "account-notify",
            "account-tag",
            "extended-join",
            "draft/chathistory",
            "sasl"
          ];
          const available = caps.split(" ").map((c) => c.split("=")[0]);
          const req = want.filter((c) => available.includes(c));
          if (req.length) {
            this.raw(`CAP REQ :${req.join(" ")}`);
          } else {
            this.raw("CAP END");
          }
        } else if (sub === "ACK") {
          const caps = (m.params[2] || "").split(" ");
          for (const c of caps) this.ackedCaps.add(c);
          if (caps.includes("sasl") && this.saslToken) {
            this.startSasl();
          } else {
            this.raw("CAP END");
          }
        }
        break;
      }
      case "AUTHENTICATE": {
        this.sendSaslResponse(m.params[0]);
        break;
      }
      case "900":
      case "903": {
        const did = this.saslDid;
        this.authenticatedDid = did;
        this.emit({ type: "authenticated", did });
        this.addServerMessage(`Authenticated as ${did}`);
        this.raw("CAP END");
        break;
      }
      case "904": {
        const reason = m.params[m.params.length - 1] || "SASL authentication failed";
        this.emit({ type: "authError", message: reason });
        this.addServerMessage(`Auth failed: ${reason}`);
        this.raw("CAP END");
        break;
      }
      case "001":
      case "002":
      case "003":
      case "004": {
        if (!this.registered && m.command === "001") {
          this.registered = true;
          this.nick = m.params[0];
          this.emit({ type: "registered", nick: this.nick });
        }
        break;
      }
      case "005": {
        break;
      }
      case "375":
      case "372": {
        const text = m.params[1] || "";
        if (m.command === "372") {
          this.emit({ type: "motd", line: text });
        }
        break;
      }
      case "PRIVMSG": {
        const from = prefixNick(m.prefix);
        const target = m.params[0] || "";
        let text = m.params[1] || "";
        const isAction = text.startsWith("ACTION ") && text.endsWith("");
        if (isAction) {
          text = text.slice(8, -1);
        }
        const ts = m.tags["time"] ? new Date(m.tags["time"]) : /* @__PURE__ */ new Date();
        const msg = {
          id: m.tags["msgid"] || this.nextLocalId(),
          from,
          text,
          timestamp: ts,
          tags: m.tags,
          isSelf: from.toLowerCase() === this.nick.toLowerCase(),
          isAction,
          replyTo: m.tags["+reply"],
          editOf: m.tags["+draft/edit"]
        };
        const displayTarget = target.toLowerCase() === this.nick.toLowerCase() ? from : target;
        this.addMessage(displayTarget, msg);
        break;
      }
      case "NOTICE": {
        const from = prefixNick(m.prefix);
        const target = m.params[0] || "";
        const text = m.params[1] || "";
        if (!from || from.toLowerCase() === this.nick.toLowerCase()) {
          this.addServerMessage(text);
        } else {
          const msg = {
            id: this.nextLocalId(),
            from,
            text,
            timestamp: /* @__PURE__ */ new Date(),
            tags: m.tags,
            isSystem: true
          };
          const displayTarget = target.toLowerCase() === this.nick.toLowerCase() ? from : target;
          this.addMessage(displayTarget, msg);
        }
        break;
      }
      case "JOIN": {
        const nick = prefixNick(m.prefix);
        const channel = m.params[0] || "";
        const ch = this.ensureChannel(channel);
        if (nick.toLowerCase() === this.nick.toLowerCase()) {
          ch.isJoined = true;
          ch.messages = [];
          this.requestHistoryLatest(channel, 50);
        }
        const did = m.tags["account"];
        const member = {
          nick,
          did,
          isOp: false,
          isVoiced: false
        };
        ch.members.set(nick.toLowerCase(), member);
        this.emit({ type: "memberJoined", channel: ch.name, nick, member });
        this.emit({ type: "channelUpdated", channel: ch.name });
        break;
      }
      case "PART": {
        const nick = prefixNick(m.prefix);
        const channel = m.params[0] || "";
        const ch = this.channels.get(channel.toLowerCase());
        if (ch) {
          ch.members.delete(nick.toLowerCase());
          if (nick.toLowerCase() === this.nick.toLowerCase()) {
            ch.isJoined = false;
          }
          this.emit({ type: "memberParted", channel: ch.name, nick });
          this.emit({ type: "channelUpdated", channel: ch.name });
        }
        break;
      }
      case "QUIT": {
        const nick = prefixNick(m.prefix);
        const reason = m.params[0] || "";
        for (const ch of this.channels.values()) {
          if (ch.members.has(nick.toLowerCase())) {
            ch.members.delete(nick.toLowerCase());
            this.emit({ type: "memberParted", channel: ch.name, nick });
            this.emit({ type: "channelUpdated", channel: ch.name });
          }
        }
        this.emit({ type: "memberQuit", nick, reason });
        break;
      }
      case "NICK": {
        const oldNick = prefixNick(m.prefix);
        const newNick = m.params[0] || "";
        if (oldNick.toLowerCase() === this.nick.toLowerCase()) {
          this.nick = newNick;
        }
        for (const ch of this.channels.values()) {
          const mbr = ch.members.get(oldNick.toLowerCase());
          if (mbr) {
            ch.members.delete(oldNick.toLowerCase());
            mbr.nick = newNick;
            ch.members.set(newNick.toLowerCase(), mbr);
            this.emit({ type: "channelUpdated", channel: ch.name });
          }
        }
        this.emit({ type: "nickChange", oldNick, newNick });
        break;
      }
      case "TOPIC": {
        const channel = m.params[0] || "";
        const topic = m.params[1] || "";
        const ch = this.ensureChannel(channel);
        ch.topic = topic;
        ch.topicSetBy = prefixNick(m.prefix);
        this.emit({ type: "topicChanged", channel: ch.name, topic, setBy: ch.topicSetBy });
        this.emit({ type: "channelUpdated", channel: ch.name });
        break;
      }
      case "332": {
        const channel = m.params[1] || "";
        const topic = m.params[2] || "";
        const ch = this.ensureChannel(channel);
        ch.topic = topic;
        this.emit({ type: "topicChanged", channel: ch.name, topic });
        this.emit({ type: "channelUpdated", channel: ch.name });
        break;
      }
      case "MODE": {
        const target = m.params[0] || "";
        const modes = m.params.slice(1);
        const ch = this.channels.get(target.toLowerCase());
        if (ch) {
          let adding = true;
          for (const token of modes) {
            if (token.startsWith("+")) {
              adding = true;
              for (let i = 1; i < token.length; i++) {
                ch.modes.add(token[i]);
              }
            } else if (token.startsWith("-")) {
              adding = false;
              for (let i = 1; i < token.length; i++) {
                ch.modes.delete(token[i]);
              }
            } else if (token.length === 2 && (token[0] === "+" || token[0] === "-")) {
              const mode = token[1];
              if (adding) ch.modes.add(mode);
              else ch.modes.delete(mode);
            }
          }
          this.emit({ type: "modeChanged", channel: ch.name, modes });
          this.emit({ type: "channelUpdated", channel: ch.name });
        }
        break;
      }
      case "353": {
        const channel = m.params[2] || "";
        const names = (m.params[3] || "").split(" ").filter(Boolean);
        const ch = this.ensureChannel(channel);
        for (const name of names) {
          let nick = name;
          let isOp = false;
          let isVoiced = false;
          if (nick.startsWith("@")) {
            isOp = true;
            nick = nick.slice(1);
          } else if (nick.startsWith("+")) {
            isVoiced = true;
            nick = nick.slice(1);
          }
          const existing = ch.members.get(nick.toLowerCase());
          if (!existing) {
            ch.members.set(nick.toLowerCase(), { nick, isOp, isVoiced });
          } else {
            existing.isOp = isOp;
            existing.isVoiced = isVoiced;
          }
        }
        this.emit({ type: "channelUpdated", channel: ch.name });
        break;
      }
      case "366": {
        break;
      }
      case "KICK": {
        const channel = m.params[0] || "";
        const kicked = m.params[1] || "";
        const by = prefixNick(m.prefix);
        const reason = m.params[2] || "";
        const ch = this.channels.get(channel.toLowerCase());
        if (ch) {
          ch.members.delete(kicked.toLowerCase());
          if (kicked.toLowerCase() === this.nick.toLowerCase()) {
            ch.isJoined = false;
          }
          this.emit({ type: "kicked", channel: ch.name, nick: kicked, by, reason });
          this.emit({ type: "channelUpdated", channel: ch.name });
        }
        break;
      }
      case "AWAY": {
        const nick = prefixNick(m.prefix);
        const away = m.params[0] || null;
        for (const ch of this.channels.values()) {
          const mbr = ch.members.get(nick.toLowerCase());
          if (mbr) {
            mbr.away = away;
            this.emit({ type: "channelUpdated", channel: ch.name });
          }
        }
        this.emit({ type: "awayChanged", nick, away });
        break;
      }
      case "ACCOUNT": {
        const nick = prefixNick(m.prefix);
        const did = m.params[0] || "";
        for (const ch of this.channels.values()) {
          const mbr = ch.members.get(nick.toLowerCase());
          if (mbr) {
            mbr.did = did;
            this.emit({ type: "channelUpdated", channel: ch.name });
          }
        }
        break;
      }
      case "BATCH": {
        const batchArg = m.params[0] || "";
        const ref = batchArg.slice(1);
        const isEnd = batchArg.startsWith("-");
        const batchType = isEnd ? "" : m.params[1] || "";
        const target = isEnd ? "" : m.params[2] || "";
        if (isEnd) {
          const batch = this.batches.get(ref);
          if (batch) {
            const ch = this.ensureChannel(batch.target);
            for (const msg of batch.messages) {
              ch.messages.unshift(msg);
            }
            this.batches.delete(ref);
            this.emit({ type: "batchEnd", ref });
            this.emit({ type: "channelUpdated", channel: ch.name });
          }
        } else {
          this.batches.set(ref, { type: batchType, target, messages: [] });
          this.emit({ type: "batchStart", ref, batchType, target });
        }
        break;
      }
      case "CHATHISTORY": {
        break;
      }
      default: {
        if (m.command.match(/^\d{3}$/)) {
          const text = m.params[m.params.length - 1] || "";
          if (!this.backgroundWhois.has((m.params[1] || "").toLowerCase())) {
            this.addServerMessage(text);
          }
        }
        break;
      }
    }
  }
  // ── SASL ──
  startSasl() {
    this.raw("AUTHENTICATE ATPROTO-CHALLENGE");
  }
  sendSaslResponse(challenge) {
    let challengeNonce;
    if (challenge && challenge !== "+") {
      try {
        const json = atob(challenge);
        const parsed = JSON.parse(json);
        challengeNonce = parsed.nonce;
      } catch {
      }
    }
    const payload = JSON.stringify({
      did: this.saslDid,
      method: this.saslMethod || "pds-session",
      signature: this.saslToken,
      pds_url: "",
      challenge_nonce: challengeNonce
    });
    const encoded = btoa(payload);
    for (let i = 0; i < encoded.length; i += 400) {
      this.raw(`AUTHENTICATE ${encoded.slice(i, i + 400)}`);
    }
    if (encoded.length % 400 === 0) {
      this.raw("AUTHENTICATE +");
    }
  }
};

// src/ui/ChatView.ts
var import_obsidian3 = require("obsidian");

// src/ui/JoinChannelModal.ts
var import_obsidian2 = require("obsidian");
var JoinChannelModal = class extends import_obsidian2.Modal {
  onSubmit;
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "Join channel" });
    const input = contentEl.createEl("input", {
      type: "text",
      placeholder: "#general"
    });
    input.style.width = "100%";
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        const value = input.value.trim();
        if (value) {
          this.close();
          this.onSubmit(value);
        }
      }
    });
    const btn = contentEl.createEl("button", {
      text: "Join",
      cls: "mod-cta"
    });
    btn.addEventListener("click", () => {
      const value = input.value.trim();
      if (value) {
        this.close();
        this.onSubmit(value);
      }
    });
    input.focus();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/ChatView.ts
var VIEW_TYPE_FREEQ = "freeq-chat";
var ChatView = class extends import_obsidian3.ItemView {
  plugin;
  container;
  channelListEl;
  messageAreaEl;
  inputEl;
  statusEl;
  memberListEl;
  toggleMembersBtn;
  showMembers = false;
  showChannelList = true;
  statusBase = "Disconnected";
  topicEditing = false;
  topicEditChannel = "";
  topicDraft = "";
  replyBannerEl;
  replyingTo = null;
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_FREEQ;
  }
  getDisplayText() {
    return "FreeQ Chat";
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    if (!this.containerEl.children[1]) {
      console.error("[chatview] containerEl.children[1] is missing \u2014 cannot build UI");
      return;
    }
    this.container = this.containerEl.children[1];
    this.container.empty();
    this.container.addClass("freeq-chat-container");
    this.buildLayout();
    this.bindEvents();
    if (this.plugin.client.isConnected()) {
      this.catchUpState();
    }
  }
  async onClose() {
    if (this.unsubEvents) {
      this.unsubEvents();
      this.unsubEvents = null;
    }
  }
  // ── Build ──
  buildLayout() {
    const header = this.container.createDiv({ cls: "freeq-header" });
    this.statusEl = header.createDiv({ cls: "freeq-status" });
    this.updateHeader();
    const headerActions = header.createDiv({ cls: "freeq-header-actions" });
    const toggleChannelsBtn = headerActions.createEl("button", {
      text: "\u2630",
      cls: "freeq-btn-small",
      attr: { title: "Toggle channel list" }
    });
    toggleChannelsBtn.addEventListener("click", () => this.toggleChannelList());
    this.toggleMembersBtn = headerActions.createEl("button", {
      text: "\u{1F465}",
      cls: "freeq-btn-small",
      attr: { title: "Toggle member list" }
    });
    this.toggleMembersBtn.addEventListener("click", () => this.toggleMembers());
    const markReadBtn = headerActions.createEl("button", {
      text: "\u2713",
      cls: "freeq-btn-small",
      attr: { title: "Mark all channels as read" }
    });
    markReadBtn.addEventListener("click", () => this.markAllRead());
    const joinBtn = headerActions.createEl("button", {
      text: "Join",
      cls: "freeq-btn-small"
    });
    joinBtn.addEventListener("click", () => this.promptJoin());
    const connectBtn = headerActions.createEl("button", {
      text: "Connect",
      cls: "freeq-btn-small mod-cta"
    });
    connectBtn.addEventListener("click", () => this.plugin.connect());
    const main = this.container.createDiv({ cls: "freeq-main" });
    this.channelListEl = main.createDiv({ cls: "freeq-channel-list" });
    this.channelListEl.createDiv({ cls: "freeq-empty", text: "No channels" });
    const msgWrap = main.createDiv({ cls: "freeq-message-wrap" });
    this.messageAreaEl = msgWrap.createDiv({ cls: "freeq-message-area" });
    this.messageAreaEl.createDiv({
      cls: "freeq-empty freeq-welcome",
      text: "FreeQ Chat\nConnect to start chatting."
    });
    this.replyBannerEl = msgWrap.createDiv({ cls: "freeq-reply-banner" });
    this.replyBannerEl.style.display = "none";
    const inputWrap = msgWrap.createDiv({ cls: "freeq-input-wrap" });
    this.inputEl = inputWrap.createEl("input", {
      cls: "freeq-input",
      attr: { placeholder: "Type a message\u2026", disabled: true }
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendInput();
      }
      if (e.key === "Escape") {
        this.cancelReply();
      }
    });
    this.inputEl.addEventListener("paste", (e) => {
      void this.handlePaste(e);
    });
    this.memberListEl = main.createDiv({ cls: "freeq-member-list" });
    this.memberListEl.style.display = "none";
  }
  // ── Event binding ──
  unsubEvents = null;
  bindEvents() {
    const client = this.plugin.client;
    this.unsubEvents = client.addListener((ev) => this.handleEvent(ev));
  }
  // ── Event handling ──
  handleEvent(ev) {
    if (ev.type !== "message" && ev.type !== "serverMessage") {
    }
    switch (ev.type) {
      case "state":
        this.updateStatus(ev.state);
        break;
      case "registered":
        this.onRegistered(ev.nick);
        break;
      case "authenticated":
        this.statusEl.setText(`Authenticated as ${ev.did.slice(0, 24)}\u2026`);
        break;
      case "authError":
        new import_obsidian3.Notice(`FreeQ auth error: ${ev.message}`);
        this.statusEl.setText(`Auth failed: ${ev.message}`);
        this.inputEl.placeholder = "Authentication failed \u2014 check settings";
        break;
      case "channelUpdated":
        this.renderChannelList();
        if (this.isActiveChannel(ev.channel)) {
          this.renderMessages();
          this.renderMembers();
        }
        break;
      case "message":
        if (this.isActiveChannel(ev.channel)) {
          this.appendMessage(ev.msg);
          this.scrollToBottom();
        }
        break;
      case "serverMessage":
        this.appendMessage(ev.msg);
        this.scrollToBottom();
        break;
      case "memberJoined":
      case "memberParted":
        if (this.isActiveChannel(ev.channel)) {
          this.renderMembers();
        }
        break;
      case "topicChanged":
        if (this.isActiveChannel(ev.channel)) {
          this.renderTopic(ev.topic);
        }
        break;
      case "batchEnd":
        if (this.plugin.client.channels.get(
          this.plugin.client.activeChannel.toLowerCase()
        )) {
          this.renderMessages();
        }
        break;
    }
  }
  // ── UI Actions ──
  updateHeader() {
    const channel = this.plugin.client.activeChannel?.trim();
    const ch = channel ? this.plugin.client.channels.get(channel.toLowerCase()) : void 0;
    const topic = ch?.topic?.trim();
    this.statusEl.empty();
    this.statusEl.createSpan({ text: this.statusBase });
    if (!channel) return;
    this.statusEl.createSpan({ text: ` \xB7 ${channel}` });
    if (!topic) return;
    const topicWrap = this.statusEl.createSpan({ text: " \xB7 " });
    if (this.topicEditing && this.topicEditChannel === channel) {
      const input = topicWrap.createEl("input", {
        cls: "freeq-topic-input",
        attr: { type: "text", "aria-label": "Edit topic" }
      });
      input.style.width = "48ch";
      input.style.maxWidth = "100%";
      input.value = this.topicDraft;
      input.addEventListener("input", () => {
        this.topicDraft = input.value;
      });
      input.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          this.commitTopicEdit();
        } else if (e.key === "Escape") {
          e.preventDefault();
          this.cancelTopicEdit();
        }
      });
      input.addEventListener("blur", () => {
        this.commitTopicEdit();
      });
      queueMicrotask(() => {
        input.focus();
        input.setSelectionRange(input.value.length, input.value.length);
      });
      return;
    }
    const topicEl = topicWrap.createSpan({ cls: "freeq-topic-text", text: topic });
    topicEl.addClass("freeq-topic-clickable");
    topicEl.setAttribute("role", "button");
    topicEl.setAttribute("tabindex", "0");
    topicEl.setAttribute("title", "Click to edit topic");
    topicEl.addEventListener("click", () => {
      this.startTopicEdit();
    });
    topicEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        this.startTopicEdit();
      }
    });
  }
  startTopicEdit() {
    const channel = this.plugin.client.activeChannel?.trim();
    if (!channel) return;
    const ch = this.plugin.client.channels.get(channel.toLowerCase());
    if (!ch || !ch.topic.trim()) return;
    this.topicEditing = true;
    this.topicEditChannel = channel;
    this.topicDraft = ch.topic;
    this.updateHeader();
  }
  commitTopicEdit() {
    if (!this.topicEditing) return;
    const channel = this.topicEditChannel;
    const topic = this.topicDraft;
    this.topicEditing = false;
    this.topicEditChannel = "";
    this.topicDraft = "";
    if (!channel) {
      this.updateHeader();
      return;
    }
    const ch = this.plugin.client.channels.get(channel.toLowerCase());
    if (ch) {
      ch.topic = topic;
    }
    this.plugin.client.raw(`TOPIC ${channel} :${topic}`);
    this.updateHeader();
  }
  cancelTopicEdit() {
    if (!this.topicEditing) return;
    this.topicEditing = false;
    this.topicEditChannel = "";
    this.topicDraft = "";
    this.updateHeader();
  }
  updateStatus(state) {
    const map = {
      disconnected: "Disconnected",
      connecting: "Connecting\u2026",
      connected: "Authenticating\u2026"
    };
    this.statusBase = map[state] || state;
    this.updateHeader();
    if (state === "connected" || state === "registered") {
      this.statusEl.addClass("freeq-status-connected");
      this.inputEl.disabled = false;
    } else {
      this.statusEl.removeClass("freeq-status-connected");
    }
  }
  onRegistered(nick) {
    this.inputEl.disabled = false;
    this.inputEl.placeholder = `Message as ${nick}\u2026`;
    this.statusBase = `Registered as ${nick}`;
    this.updateHeader();
    this.renderChannelList();
    this.renderMessages();
  }
  catchUpState() {
    const nick = this.plugin.client.currentNick;
    this.inputEl.disabled = false;
    this.inputEl.placeholder = `Message as ${nick}\u2026`;
    this.statusBase = `Registered as ${nick}`;
    this.updateHeader();
    this.renderChannelList();
    this.renderMessages();
  }
  sendInput() {
    const text = this.inputEl.value.trim();
    if (!text) return;
    this.inputEl.value = "";
    const target = this.plugin.client.activeChannel;
    if (!target) {
      new import_obsidian3.Notice("Join a channel first.");
      return;
    }
    if (text.startsWith("/")) {
      this.handleCommand(text.slice(1));
      return;
    }
    this.plugin.client.sendPrivmsg(target, text, this.replyingTo?.id);
    this.cancelReply();
  }
  async handlePaste(e) {
    const file = await this.getPastedFile(e);
    if (!file) return;
    e.preventDefault();
    e.stopPropagation();
    console.warn("[freeq] paste file", {
      name: file.name,
      type: file.type,
      size: file.size,
      channel: this.plugin.client.activeChannel
    });
    try {
      const url = await this.plugin.uploadBlobToPds(file, file.name || "paste.bin");
      if (!url) return;
      this.insertTextAtCursor(url);
      new import_obsidian3.Notice("Pasted file uploaded.");
    } catch (err) {
      new import_obsidian3.Notice(`File upload failed: ${err?.message || String(err)}`);
    }
  }
  async getPastedFile(e) {
    const items = e.clipboardData?.items;
    if (items) {
      for (const item of items) {
        if (item.kind !== "file") continue;
        const file = item.getAsFile();
        if (file) return file;
      }
    }
    const clipboard = navigator.clipboard;
    if (clipboard?.read) {
      try {
        const clipboardItems = await clipboard.read();
        for (const item of clipboardItems) {
          for (const type of item.types) {
            const blob = await item.getType(type);
            return new File([blob], `paste-${Date.now()}.${this.extensionForMime(type)}`, {
              type
            });
          }
        }
      } catch (error) {
        console.warn("[freeq] navigator clipboard read failed:", error);
      }
    }
    return null;
  }
  extensionForMime(type) {
    if (type === "image/png") return "png";
    if (type === "image/jpeg") return "jpg";
    if (type === "image/webp") return "webp";
    if (type === "image/gif") return "gif";
    if (type === "text/plain") return "txt";
    if (type === "application/pdf") return "pdf";
    return "bin";
  }
  insertTextAtCursor(text) {
    const el = this.inputEl;
    const start = el.selectionStart ?? el.value.length;
    const end = el.selectionEnd ?? el.value.length;
    const value = el.value;
    el.value = value.slice(0, start) + text + value.slice(end);
    const next = start + text.length;
    el.focus();
    el.setSelectionRange(next, next);
  }
  handleCommand(cmd) {
    const [name, ...rest] = cmd.split(" ");
    const args = rest.join(" ");
    const client = this.plugin.client;
    switch (name.toLowerCase()) {
      case "join":
      case "j":
        if (args) client.join(args.split(" ")[0]);
        break;
      case "part":
      case "leave":
        client.part(args || client.activeChannel);
        break;
      case "quit":
        client.raw("QUIT :Leaving");
        break;
      case "nick":
        if (args) client.raw(`NICK ${args}`);
        break;
      case "msg":
      case "query": {
        const [to, ...msgParts] = args.split(" ");
        if (to && msgParts.length) {
          client.sendPrivmsg(to, msgParts.join(" "));
          client.ensureChannel(to);
          client.activeChannel = to;
          this.renderChannelList();
          this.renderMessages();
        }
        break;
      }
      case "whois":
        if (args) client.whois(args);
        break;
      case "me":
        client.sendAction(client.activeChannel, args);
        break;
      default:
        client.raw(name.toUpperCase() + " " + args);
    }
  }
  promptJoin() {
    if (!this.plugin.client.isConnected()) {
      new import_obsidian3.Notice("Not connected to server.");
      return;
    }
    new JoinChannelModal(this.app, (channel) => {
      this.plugin.client.join(channel);
    }).open();
  }
  toggleMembers() {
    this.showMembers = !this.showMembers;
    this.memberListEl.style.display = this.showMembers ? "block" : "none";
    this.toggleMembersBtn.toggleClass("freeq-btn-active", this.showMembers);
    if (this.showMembers) {
      this.renderMembers();
    }
  }
  toggleChannelList() {
    this.showChannelList = !this.showChannelList;
    this.channelListEl.style.display = this.showChannelList ? "" : "none";
  }
  markAllRead() {
    for (const ch of this.plugin.client.channels.values()) {
      ch.unreadCount = 0;
    }
    this.renderChannelList();
  }
  // ── Rendering ──
  isActiveChannel(name) {
    return name.toLowerCase() === this.plugin.client.activeChannel.toLowerCase();
  }
  renderChannelList() {
    this.updateHeader();
    this.channelListEl.empty();
    const channels = Array.from(this.plugin.client.channels.values());
    if (!channels.length) {
      this.channelListEl.createDiv({ cls: "freeq-empty", text: "No channels \u2014 use the Join button or set auto-join channels in settings." });
      return;
    }
    for (const ch of channels) {
      const el = this.channelListEl.createDiv({
        cls: "freeq-channel",
        text: ch.name
      });
      if (this.isActiveChannel(ch.name)) {
        el.addClass("freeq-channel-active");
      }
      if (!ch.isJoined) {
        el.addClass("freeq-channel-parted");
      }
      if (ch.unreadCount > 0 && !this.isActiveChannel(ch.name)) {
        const badge = el.createSpan({ cls: "freeq-unread-badge" });
        badge.setText(String(ch.unreadCount));
      }
      el.addEventListener("click", () => {
        this.plugin.client.activeChannel = ch.name;
        ch.unreadCount = 0;
        this.renderChannelList();
        this.renderMessages();
        this.renderMembers();
        this.renderTopic(ch.topic);
      });
      el.addEventListener("contextmenu", (e) => {
        e.preventDefault();
        const menu = new import_obsidian3.Menu();
        if (ch.isJoined) {
          menu.addItem(
            (item) => item.setTitle("Part channel").onClick(() => {
              this.plugin.client.part(ch.name);
            })
          );
        }
        menu.showAtMouseEvent(e);
      });
    }
  }
  renderMessages() {
    this.messageAreaEl.empty();
    const ch = this.plugin.client.channels.get(
      this.plugin.client.activeChannel.toLowerCase()
    );
    if (!ch) {
      this.messageAreaEl.createDiv({
        cls: "freeq-empty",
        text: "Select or join a channel to start chatting."
      });
      return;
    }
    for (const msg of ch.messages) {
      this.renderMessage(msg);
    }
    this.scrollToBottom();
  }
  appendMessage(msg) {
    this.renderMessage(msg);
  }
  renderMessage(msg) {
    const el = this.messageAreaEl.createDiv({ cls: "freeq-message" });
    el.setAttribute("data-msg-id", msg.id);
    if (msg.isSystem) el.addClass("freeq-message-system");
    if (msg.isSelf) el.addClass("freeq-message-self");
    if (msg.isAction) el.addClass("freeq-message-action");
    if (msg.deleted) el.addClass("freeq-message-deleted");
    if (msg.replyTo) {
      const parent = this.findMessageInChannel(msg.replyTo);
      const indicator = el.createDiv({ cls: "freeq-reply-indicator" });
      indicator.createSpan({ cls: "freeq-reply-bar" });
      const author = indicator.createSpan({ cls: "freeq-reply-author" });
      const preview = indicator.createSpan({ cls: "freeq-reply-text" });
      if (parent) {
        author.setText(`@${parent.from}`);
        preview.setText(this.truncateText(parent.text, 80));
        indicator.addEventListener("click", () => this.scrollToMessage(msg.replyTo));
      } else {
        author.setText("@?");
        preview.setText("Original message");
      }
    }
    const meta = el.createDiv({ cls: "freeq-message-meta" });
    if (!msg.isSystem && msg.from) {
      const nick = meta.createSpan({ cls: "freeq-message-nick" });
      nick.setText(msg.from);
    }
    const time = meta.createSpan({ cls: "freeq-message-time" });
    time.setText(this.formatTime(msg.timestamp));
    const body = el.createDiv({ cls: "freeq-message-body" });
    if (msg.isAction && msg.from) {
      body.setText(`* ${msg.from} ${msg.text}`);
    } else {
      this.renderMessageBody(body, msg.text, msg);
    }
    el.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showMessageMenu(e, msg, this.plugin.client.activeChannel);
    });
  }
  findMessageInChannel(msgId) {
    const ch = this.plugin.client.channels.get(
      this.plugin.client.activeChannel.toLowerCase()
    );
    if (!ch) return void 0;
    return ch.messages.find((m) => m.id === msgId);
  }
  scrollToMessage(msgId) {
    const el = this.messageAreaEl.querySelector(`[data-msg-id="${msgId}"]`);
    if (!el) return;
    el.scrollIntoView({ behavior: "smooth", block: "center" });
    el.addClass("freeq-message-highlight");
    setTimeout(() => el.removeClass("freeq-message-highlight"), 1500);
  }
  truncateText(text, max) {
    if (text.length <= max) return text;
    return text.slice(0, max - 1) + "\u2026";
  }
  // ── Linkify ──
  renderMessageBody(el, text, msg) {
    const mdLinkRe = /\[([^\]]+)\]\(([^)]+)\)/g;
    const urlRe = /https?:\/\/[^\s)>,\]]+/g;
    const matches = [];
    let m;
    while ((m = mdLinkRe.exec(text)) !== null) {
      matches.push({ start: m.index, end: m.index + m[0].length, text: m[1], url: m[2], isMarkdown: true });
    }
    while ((m = urlRe.exec(text)) !== null) {
      const inside = matches.some((lm) => m.index >= lm.start && m.index < lm.end);
      if (!inside) {
        matches.push({ start: m.index, end: m.index + m[0].length, text: m[0], url: m[0], isMarkdown: false });
      }
    }
    matches.sort((a, b) => a.start - b.start);
    if (matches.length === 0) {
      el.setText(text);
      return;
    }
    let lastEnd = 0;
    for (const lm of matches) {
      if (lm.start > lastEnd) {
        el.appendChild(document.createTextNode(text.slice(lastEnd, lm.start)));
      }
      const a = el.createEl("a", {
        cls: "freeq-link",
        text: lm.text,
        attr: { href: lm.url }
      });
      a.addEventListener("click", (e) => {
        e.preventDefault();
        window.require("electron").shell.openExternal(lm.url);
      });
      const copyBtn = el.createEl("button", {
        cls: "freeq-copy-link-btn",
        attr: { title: "Copy link" }
      });
      copyBtn.setText("\u{1F4CB}");
      copyBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        e.preventDefault();
        window.require("electron").clipboard.writeText(lm.url);
      });
      lastEnd = lm.end;
    }
    if (lastEnd < text.length) {
      el.appendChild(document.createTextNode(text.slice(lastEnd)));
    }
  }
  showMessageMenu(event, msg, channel) {
    const menu = new import_obsidian3.Menu();
    menu.addItem(
      (item) => item.setTitle("Clip message to vault").setIcon("Pin").onClick(async () => {
        const path = await this.plugin.clipper.clip({ channel, msg });
        if (path) {
          new import_obsidian3.Notice(`Clipped to ${path}`);
        } else {
          new import_obsidian3.Notice("Failed to clip message.");
        }
      })
    );
    menu.addItem(
      (item) => item.setTitle("Reply").setIcon("Reply").onClick(() => {
        this.startReplyingTo(msg);
      })
    );
    if (msg.replyTo) {
      menu.addItem(
        (item) => item.setTitle("View thread").onClick(() => {
        })
      );
    }
    menu.showAtMouseEvent(event);
  }
  startReplyingTo(msg) {
    this.replyingTo = {
      id: msg.id,
      from: msg.from,
      preview: this.truncateText(msg.text, 80)
    };
    this.replyBannerEl.empty();
    this.replyBannerEl.style.display = "flex";
    const text = this.replyBannerEl.createSpan({});
    text.setText(`\u21B3 @${msg.from}: ${this.truncateText(msg.text, 80)}`);
    const cancelBtn = this.replyBannerEl.createEl("button", {
      cls: "freeq-reply-cancel",
      text: "\u2715"
    });
    cancelBtn.addEventListener("click", () => this.cancelReply());
    this.inputEl.placeholder = `Reply to @${msg.from}\u2026`;
    this.inputEl.focus();
  }
  cancelReply() {
    this.replyingTo = null;
    this.replyBannerEl.style.display = "none";
    this.replyBannerEl.empty();
    const nick = this.plugin.client.currentNick;
    this.inputEl.placeholder = nick ? `Message as ${nick}\u2026` : "Type a message\u2026";
  }
  renderMembers() {
    this.memberListEl.empty();
    const ch = this.plugin.client.channels.get(
      this.plugin.client.activeChannel.toLowerCase()
    );
    if (!ch) return;
    const title = this.memberListEl.createDiv({ cls: "freeq-member-title" });
    title.setText(`Members (${ch.members.size})`);
    const list = this.memberListEl.createDiv({ cls: "freeq-member-items" });
    const members = Array.from(ch.members.values()).sort(
      (a, b) => a.nick.localeCompare(b.nick)
    );
    for (const m of members) {
      const el = list.createDiv({ cls: "freeq-member" });
      let prefix = "";
      if (m.isOp) prefix = "@";
      else if (m.isVoiced) prefix = "+";
      el.setText(`${prefix}${m.nick}`);
      if (m.away) el.addClass("freeq-member-away");
    }
  }
  renderTopic(_topic) {
    this.updateHeader();
  }
  scrollToBottom() {
    this.messageAreaEl.scrollTop = this.messageAreaEl.scrollHeight;
  }
  formatTime(d) {
    return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  }
};

// src/clip/clipper.ts
var import_obsidian5 = require("obsidian");

// src/ui/ClipLinkModal.ts
var import_obsidian4 = require("obsidian");
var CREATE_NEW = "__create_new__";
var ClipLinkModal = class extends import_obsidian4.FuzzySuggestModal {
  onSubmit;
  defaultName;
  constructor(app, defaultName, onSubmit) {
    super(app);
    this.defaultName = defaultName;
    this.onSubmit = onSubmit;
    this.setPlaceholder("Select a note or create a new one\u2026");
  }
  getItems() {
    return [CREATE_NEW, ...this.app.vault.getMarkdownFiles().map((file) => file.path)];
  }
  getItemText(item) {
    return item === CREATE_NEW ? `\u270F\uFE0F Create new note: ${this.defaultName}` : item;
  }
  onChooseItem(item) {
    if (item === CREATE_NEW) {
      const fileName = this.defaultName.endsWith(".md") ? this.defaultName : `${this.defaultName}.md`;
      this.onSubmit(fileName);
      return;
    }
    this.onSubmit(item);
  }
};

// src/clip/clipper.ts
var Clipper = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  app;
  settings;
  async clip(context) {
    const { channel, msg } = context;
    const timestamp = (0, import_obsidian5.moment)(msg.timestamp).format("YYYY-MM-DD HH:mm:ss");
    let text = this.settings.clipTemplate.replace(/{{text}}/g, msg.text).replace(/{{from}}/g, msg.from).replace(/{{channel}}/g, channel).replace(/{{timestamp}}/g, timestamp).replace(/{{msgid}}/g, msg.id).replace(
      /{{url}}/g,
      `https://irc.freeq.at/channel/${encodeURIComponent(channel)}/msg/${msg.id}`
    );
    text = "\n" + text + "\n";
    try {
      if (this.settings.useDailyNote) {
        return await this.appendToDailyNote(text);
      } else {
        return await this.appendToFolder(text, channel, msg);
      }
    } catch (e) {
      console.error("[freeq] clip failed:", e);
      return null;
    }
  }
  async clipLink(context) {
    const { url, text, channel, msg } = context;
    const notePath = await new Promise((resolve) => {
      const defaultName = text || this.slugifyUrl(url);
      let submitted = false;
      const modal = new ClipLinkModal(this.app, defaultName, (path) => {
        submitted = true;
        resolve(path);
      });
      const origOnClose = modal.onClose.bind(modal);
      modal.onClose = () => {
        origOnClose();
        if (!submitted) resolve(null);
      };
      modal.open();
    });
    if (!notePath) return null;
    let body = "";
    try {
      const res = await (0, import_obsidian5.requestUrl)({ url, method: "GET" });
      body = res.text;
    } catch (e) {
      console.warn("[freeq] clipLink fetch failed:", url, e);
      body = "";
    }
    const timestamp = (0, import_obsidian5.moment)(msg.timestamp).format("YYYY-MM-DD HH:mm:ss");
    const frontmatter = [
      "---",
      `source: ${url}`,
      `clipped: ${(0, import_obsidian5.moment)().format("YYYY-MM-DDTHH:mm:ssZ")}`,
      `from: ${msg.from}`,
      `channel: ${channel}`,
      "---",
      ""
    ].join("\n");
    const linkLine = `> [${text}](${url}) \u2014 @${msg.from} in ${channel} at ${timestamp}

`;
    let content = "";
    if (body.startsWith("<") || body.includes("<html")) {
      const titleMatch = body.match(/<title[^>]*>([^<]+)<\/title>/i);
      const title = titleMatch ? titleMatch[1].trim() : "";
      const stripped = body.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "").replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "").replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, " ").replace(/\s+/g, " ").trim();
      content = title ? `## ${title}

${stripped.slice(0, 1e4)}` : stripped.slice(0, 1e4);
    } else {
      content = body.slice(0, 1e4);
    }
    const targetPath = (0, import_obsidian5.normalizePath)(
      notePath.includes("/") ? notePath : `${this.settings.clipFolder || "FreeQ Clippings"}/${notePath}`
    );
    const noteTitle = targetPath.replace(/\.md$/, "").split("/").pop() || notePath;
    const noteText = frontmatter + `# ${noteTitle}

` + linkLine + content + "\n";
    const existing = this.app.vault.getAbstractFileByPath(targetPath);
    if (existing instanceof import_obsidian5.TFile) {
      const appendText = "\n" + linkLine + content + "\n";
      try {
        await this.app.vault.append(existing, appendText);
        return existing.path;
      } catch (e) {
        console.error("[freeq] clipLink vault.append failed:", e);
        new import_obsidian5.Notice(`Failed to append to note: ${e.message || String(e)}`);
        return null;
      }
    }
    const folderPath = targetPath.includes("/") ? targetPath.substring(0, targetPath.lastIndexOf("/")) : this.settings.clipFolder || "FreeQ Clippings";
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    const filePath = targetPath;
    try {
      const created = await this.app.vault.create(filePath, noteText.replace(/^# .+\n\n/, `# ${noteTitle}

`));
      return created.path;
    } catch (e) {
      console.error("[freeq] clipLink vault.create failed:", e);
      new import_obsidian5.Notice(`Failed to clip link: ${e.message || String(e)}`);
      return null;
    }
  }
  slugifyUrl(url) {
    try {
      const u = new URL(url);
      const path = u.pathname.replace(/\/$/, "").split("/").pop() || "";
      const name = path.replace(/\.[^.]+$/, "").replace(/[^a-zA-Z0-9_-]/g, " ").trim();
      return name || u.hostname;
    } catch {
      return "clipped-link";
    }
  }
  async appendToDailyNote(text) {
    const dailyNotes = this.app.internal?.plugins?.plugins?.["daily-notes"];
    if (dailyNotes?.instance) {
      const file2 = await dailyNotes.instance.openOrCreate((0, import_obsidian5.moment)());
      if (file2 instanceof import_obsidian5.TFile) {
        await this.app.vault.append(file2, text);
        return file2.path;
      }
    }
    const dateStr = (0, import_obsidian5.moment)().format(this.settings.dailyNoteFormat || "YYYY-MM-DD");
    const path = (0, import_obsidian5.normalizePath)(`${dateStr}.md`);
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian5.TFile) {
      await this.app.vault.append(file, text);
      return file.path;
    }
    const created = await this.app.vault.create(path, `# ${dateStr}
${text}`);
    return created.path;
  }
  async appendToFolder(text, channel, msg) {
    const folderPath = (0, import_obsidian5.normalizePath)(this.settings.clipFolder || "FreeQ Clippings");
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    const dateStr = (0, import_obsidian5.moment)(msg.timestamp).format("YYYY-MM-DD");
    const safeChannel = channel.replace(/[^a-zA-Z0-9_-]/g, "_");
    const fileName = `${dateStr} ${safeChannel}.md`;
    const filePath = (0, import_obsidian5.normalizePath)(`${folderPath}/${fileName}`);
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian5.TFile) {
      await this.app.vault.append(existing, text);
      return existing.path;
    }
    const header = `# ${channel} \u2014 ${dateStr}

`;
    const created = await this.app.vault.create(filePath, header + text);
    return created.path;
  }
};

// src/auth/oauth.ts
var import_obsidian6 = require("obsidian");

// src/auth/local-oauth.ts
var httpModule = null;
try {
  httpModule = require("http");
} catch {
}
function isLocalServerAvailable() {
  return httpModule !== null;
}
async function startLocalOAuthServer(decodeSession, timeoutMs = 5 * 60 * 1e3) {
  if (!httpModule) {
    throw new Error("Local HTTP server not available in this environment.");
  }
  const server = httpModule.createServer();
  let callbackResolver = null;
  let callbackRejecter = null;
  let callbackTimer = null;
  let port = 0;
  const cleanup = () => {
    if (callbackTimer) {
      clearTimeout(callbackTimer);
      callbackTimer = null;
    }
    try {
      server.close();
    } catch {
    }
  };
  const waitForSession = () => new Promise((resolve, reject) => {
    callbackResolver = resolve;
    callbackRejecter = reject;
  });
  server.on("request", (req, res) => {
    const reqUrl = req.url || "";
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type");
    if (req.method === "OPTIONS") {
      res.writeHead(200);
      res.end();
      return;
    }
    if (reqUrl.startsWith("/done")) {
      const query = new URL(reqUrl, `http://127.0.0.1:${port}`).searchParams;
      const oauthData = query.get("oauth");
      res.writeHead(200, { "Content-Type": "text/html" });
      res.end(`<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Authenticated</title>
<style>body{font-family:system-ui,sans-serif;background:#1e1e2e;color:#cdd6f4;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;}</style>
</head><body><div style="text-align:center;"><h1>\u2705 Authenticated</h1><p>You can close this tab and return to Obsidian.</p></div></body></html>`);
      if (oauthData) {
        try {
          const session = decodeSession(oauthData);
          cleanup();
          callbackResolver?.(session);
        } catch (e) {
          cleanup();
          callbackRejecter?.(
            new Error(
              `Failed to decode session: ${e instanceof Error ? e.message : String(e)}`
            )
          );
        }
      } else {
        cleanup();
        callbackRejecter?.(new Error("No OAuth data received from callback."));
      }
      return;
    }
    if (reqUrl.startsWith("/callback")) {
      res.writeHead(200, { "Content-Type": "text/html" });
      res.end(`<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>FreeQ OAuth</title>
<style>body{font-family:system-ui,sans-serif;background:#1e1e2e;color:#cdd6f4;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;}</style>
</head><body>
<div style="text-align:center;"><h1>Connecting to Obsidian...</h1><div class="spinner" style="margin:2rem auto;width:40px;height:40px;border:4px solid #1e293b;border-top:4px solid #38bdf8;border-radius:50%;animation:spin 1s linear infinite;"></div>
<p style="color:#94a3b8;">Redirecting...</p></div>
<style>@keyframes spin{0%{transform:rotate(0deg);}100%{transform:rotate(360deg);}}</style>
<script>
(function(){
  try {
    const params = new URLSearchParams(window.location.hash.slice(1));
    const oauth = params.get('oauth');
    if (!oauth) { document.body.innerHTML = '<div style="text-align:center;"><h1>Error</h1><p>No OAuth data found.</p></div>'; return; }
    fetch('/done?oauth=' + encodeURIComponent(oauth)).then(function(){
      document.body.innerHTML = '<div style="text-align:center;"><h1>Authenticated</h1><p style="color:#a6e3a1;">Return to Obsidian.</p></div>';
    }).catch(function(){
      document.body.innerHTML = '<div style="text-align:center;"><h1>Error</h1><p>Could not communicate with Obsidian.</p></div>';
    });
  } catch(e) {
    document.body.innerHTML = '<div style="text-align:center;"><h1>Error</h1><p>' + e.message + '</p></div>';
  }
})();
<\/script>
</body></html>`);
      return;
    }
    res.writeHead(404);
    res.end("Not found");
  });
  return new Promise((resolve, reject) => {
    server.listen(0, "127.0.0.1", () => {
      const addr = server.address();
      if (!addr || typeof addr === "string") {
        cleanup();
        reject(new Error("Failed to bind to localhost"));
        return;
      }
      port = addr.port;
      const url = `http://127.0.0.1:${port}`;
      callbackTimer = setTimeout(() => {
        cleanup();
        callbackRejecter?.(
          new Error("OAuth callback timed out after 5 minutes")
        );
      }, timeoutMs);
      resolve({ url, waitForSession, cleanup });
    });
    server.on("error", (err) => {
      cleanup();
      reject(err);
    });
  });
}

// src/auth/oauth.ts
var OAuthHandler = class {
  callbackResolver = null;
  callbackRejecter = null;
  callbackTimeout = null;
  async initiate(handle, brokerBase, fallbackCallbackUrl) {
    this.cancel();
    try {
      const check = await (0, import_obsidian6.requestUrl)(`${brokerBase}/health`);
      if (check.status >= 400) {
        throw new Error("Authentication service unavailable.");
      }
    } catch (e) {
      if (e?.name === "TimeoutError" || e?.message?.includes("timeout")) {
        throw new Error("Authentication service timed out.");
      }
      throw new Error("Authentication service unreachable.");
    }
    if (isLocalServerAvailable()) {
      try {
        return await this.initiateLocal(handle, brokerBase);
      } catch (e) {
        console.warn("[freeq] local OAuth server failed, falling back:", e);
      }
    }
    if (!fallbackCallbackUrl) {
      throw new Error(
        "OAuth callback URL is not configured. Set it in FreeQ Chat settings or use App Password."
      );
    }
    return this.initiateExternal(handle, brokerBase, fallbackCallbackUrl);
  }
  async initiateLocal(handle, brokerBase) {
    const { url, waitForSession, cleanup } = await startLocalOAuthServer(
      this.decodeSession.bind(this)
    );
    const callbackUrl = `${url}/callback`;
    const authUrl = `${brokerBase}/auth/login?handle=${encodeURIComponent(
      handle
    )}&return_to=${encodeURIComponent(callbackUrl)}`;
    window.open(authUrl, "_blank");
    new import_obsidian6.Notice("Continue login in your browser\u2026");
    try {
      const session = await waitForSession();
      return session;
    } catch (e) {
      cleanup();
      throw e;
    }
  }
  async initiateExternal(handle, brokerBase, callbackUrl) {
    const authUrl = `${brokerBase}/auth/login?handle=${encodeURIComponent(
      handle
    )}&return_to=${encodeURIComponent(callbackUrl)}`;
    const waitForCallback = new Promise((resolve, reject) => {
      this.callbackResolver = resolve;
      this.callbackRejecter = reject;
      this.callbackTimeout = setTimeout(() => {
        if (this.callbackRejecter) {
          this.callbackRejecter(
            new Error("OAuth callback timed out after 5 minutes")
          );
          this.cleanup();
        }
      }, 5 * 6e4);
    });
    window.open(authUrl, "_blank");
    new import_obsidian6.Notice("Continue login in your browser\u2026");
    return waitForCallback;
  }
  /** Called by registerObsidianProtocolHandler when obsidian://freeq-chat fires.
   *  Returns the decoded session so the caller can persist it even if there is
   *  no pending promise (e.g. app was restarted before the callback arrived).
   */
  handleCallback(params) {
    const oauthData = params.get("oauth");
    if (!oauthData) {
      this.reject(new Error("Missing OAuth data in protocol callback."));
      return null;
    }
    try {
      const session = this.decodeSession(oauthData);
      if (this.callbackResolver) {
        if (this.callbackTimeout) {
          clearTimeout(this.callbackTimeout);
          this.callbackTimeout = null;
        }
        this.callbackResolver(session);
        this.cleanup();
      }
      return session;
    } catch (e) {
      this.reject(
        new Error(
          `Failed to parse OAuth callback: ${e instanceof Error ? e.message : String(e)}`
        )
      );
      return null;
    }
  }
  decodeSession(base64urlData) {
    let base64 = base64urlData.replace(/-/g, "+").replace(/_/g, "/");
    while (base64.length % 4) {
      base64 += "=";
    }
    const json = atob(base64);
    const data = JSON.parse(json);
    if (!data.did) {
      throw new Error("OAuth response missing DID.");
    }
    return {
      did: data.did,
      handle: data.handle || "",
      nick: data.nick || "",
      webToken: data.token || "",
      brokerToken: data.broker_token || "",
      pdsUrl: data.pds_url || "",
      createdAt: Date.now()
    };
  }
  reject(reason) {
    if (this.callbackRejecter) {
      if (this.callbackTimeout) {
        clearTimeout(this.callbackTimeout);
        this.callbackTimeout = null;
      }
      this.callbackRejecter(reason);
      this.cleanup();
    }
  }
  cancel() {
    if (this.callbackTimeout) {
      clearTimeout(this.callbackTimeout);
      this.callbackTimeout = null;
    }
    if (this.callbackRejecter) {
      this.callbackRejecter(new Error("OAuth flow cancelled."));
    }
    this.cleanup();
  }
  cleanup() {
    this.callbackResolver = null;
    this.callbackRejecter = null;
    this.callbackTimeout = null;
  }
};

// src/pds/blob.ts
var import_obsidian7 = require("obsidian");
var BlobUploadError = class extends Error {
  status;
  body;
  constructor(status, body) {
    super(typeof body === "string" ? body : body.message || `Upload failed (${status})`);
    this.name = "BlobUploadError";
    this.status = status;
    this.body = body;
  }
};
function toBytes(content) {
  if (typeof content === "string") {
    return new TextEncoder().encode(content);
  }
  if (content instanceof Uint8Array) {
    return content;
  }
  return new Uint8Array(content);
}
function concatBytes(...chunks) {
  const total = chunks.reduce((sum, chunk) => sum + chunk.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    out.set(chunk, offset);
    offset += chunk.length;
  }
  return out;
}
async function uploadBlobViaFreeQ(opts) {
  const { serverUrl, did, content, filename, mimeType } = opts;
  const endpoint = serverUrl.replace(/\/$/, "") + "/api/v1/upload";
  const boundary = "----FreeQBlobBoundary" + Math.random().toString(36).slice(2);
  const name = filename || "note.md";
  const type = mimeType || "text/markdown";
  const encoder = new TextEncoder();
  const body = concatBytes(
    encoder.encode(
      `--${boundary}\r
Content-Disposition: form-data; name="did"\r
\r
${did}\r
`
    ),
    encoder.encode(
      `--${boundary}\r
Content-Disposition: form-data; name="file"; filename="${name}"\r
Content-Type: ${type}\r
\r
`
    ),
    toBytes(content),
    encoder.encode(`\r
--${boundary}--\r
`)
  );
  const res = await (0, import_obsidian7.requestUrl)({
    url: endpoint,
    method: "POST",
    contentType: `multipart/form-data; boundary=${boundary}`,
    throw: false,
    body: body.buffer.slice(body.byteOffset, body.byteOffset + body.byteLength)
  });
  if (res.status >= 400) {
    let body2 = res.text;
    try {
      body2 = JSON.parse(res.text);
    } catch {
    }
    console.warn("[freeq] upload blob failed", {
      status: res.status,
      filename: name,
      mimeType: type,
      response: res.text.slice(0, 500),
      headers: res.headers
    });
    throw new BlobUploadError(res.status, body2);
  }
  const data = res.json;
  if (!data.url) {
    throw new Error("Upload response missing URL");
  }
  return { cid: data.cid, url: data.url };
}

// src/main.ts
var FreeQPlugin = class extends import_obsidian8.Plugin {
  settings;
  client;
  clipper;
  oauth;
  async onload() {
    await this.loadSettings();
    this.client = new IRCClient();
    if (this.settings.lastChannel) {
      this.client.activeChannel = this.settings.lastChannel;
    }
    this.client.onActiveChannelChange = (channel) => {
      if (channel && channel !== this.settings.lastChannel) {
        this.settings.lastChannel = channel;
        void this.saveSettings();
      }
    };
    this.clipper = new Clipper(this.app, this.settings);
    this.oauth = new OAuthHandler();
    this.registerView(VIEW_TYPE_FREEQ, (leaf) => new ChatView(leaf, this));
    this.registerObsidianProtocolHandler("freeq-chat", (params) => {
      try {
        const urlParams = new URLSearchParams();
        for (const [key, value] of Object.entries(params)) {
          if (value) urlParams.set(key, String(value));
        }
        const session = this.oauth.handleCallback(urlParams);
        if (session) {
          this.settings.oauthSession = session;
          this.settings.did = session.did;
          this.settings.lastHandle = session.handle;
          this.saveSettings();
          new import_obsidian8.Notice("Authentication completed! Connecting\u2026");
          this.connect();
        }
      } catch (error) {
        console.error("[freeq] protocol handler error:", error);
        new import_obsidian8.Notice("Authentication error.");
      }
    });
    this.addRibbonIcon("message-circle", "Open FreeQ Chat", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-freeq-chat",
      name: "Open chat sidebar",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "open-freeq-chat-popout",
      name: "Open chat in popout window",
      callback: () => this.openChatInPopout()
    });
    this.addCommand({
      id: "freeq-connect",
      name: "Connect to server",
      callback: () => this.connect()
    });
    this.addCommand({
      id: "freeq-disconnect",
      name: "Disconnect from server",
      callback: () => this.disconnect()
    });
    this.addCommand({
      id: "freeq-join-channel",
      name: "Join channel",
      callback: () => {
        if (!this.client.isConnected()) {
          new import_obsidian8.Notice("Not connected to server.");
          return;
        }
        new JoinChannelModal(this.app, (channel) => {
          this.client.join(channel);
        }).open();
      }
    });
    this.addCommand({
      id: "freeq-send-message",
      name: "Send message to active channel",
      callback: () => {
        const text = prompt("Message:");
        if (text?.trim()) {
          const target = this.client.activeChannel;
          if (target) {
            this.client.sendPrivmsg(target, text.trim());
          } else {
            new import_obsidian8.Notice("No active channel.");
          }
        }
      }
    });
    this.addCommand({
      id: "freeq-upload-blob",
      name: "Upload note to PDS blob",
      callback: () => this.uploadNoteBlob()
    });
    this.addSettingTab(new FreeQSettingTab(this.app, this));
    if (this.settings.oauthSession) {
      setTimeout(() => this.connect(), 1500);
    }
  }
  onunload() {
    this.disconnect();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.clipper = new Clipper(this.app, this.settings);
  }
  // ── OAuth ──
  async initiateOAuth(handle) {
    const session = await this.oauth.initiate(
      handle,
      this.settings.brokerUrl,
      this.settings.callbackUrl
    );
    this.settings.oauthSession = session;
    this.settings.did = session.did;
    this.settings.lastHandle = session.handle;
    await this.saveSettings();
  }
  // ── Connection ──
  isConnecting = false;
  registrationTimer = null;
  async connect() {
    if (this.isConnecting) {
      new import_obsidian8.Notice("Connection already in progress.");
      return;
    }
    this.isConnecting = true;
    const { serverUrl, nick, oauthSession, did, appPassword, pdsUrl, brokerUrl } = this.settings;
    if (!serverUrl) {
      this.isConnecting = false;
      new import_obsidian8.Notice("FreeQ server URL is not configured.");
      return;
    }
    let token = "";
    let method = "";
    let effectiveDid = did;
    if (oauthSession?.brokerToken) {
      try {
        const refreshed = await this.refreshBrokerToken(oauthSession.brokerToken);
        this.settings.oauthSession = {
          ...oauthSession,
          webToken: refreshed.token,
          nick: refreshed.nick,
          did: refreshed.did,
          handle: refreshed.handle,
          createdAt: Date.now()
        };
        this.settings.lastHandle = refreshed.handle;
        await this.saveSettings();
        token = refreshed.token;
        method = "web-token";
        effectiveDid = refreshed.did;
      } catch (e) {
        console.error("[freeq] broker refresh failed:", e);
        const handle = oauthSession?.handle;
        if (handle) {
          try {
            new import_obsidian8.Notice("Session expired \u2014 re-authenticating\u2026");
            await this.initiateOAuth(handle);
            const refreshed = await this.refreshBrokerToken(this.settings.oauthSession.brokerToken);
            this.settings.oauthSession = {
              ...this.settings.oauthSession,
              webToken: refreshed.token,
              nick: refreshed.nick,
              did: refreshed.did,
              handle: refreshed.handle,
              createdAt: Date.now()
            };
            await this.saveSettings();
            token = refreshed.token;
            method = "web-token";
            effectiveDid = refreshed.did;
          } catch (reauthErr) {
            this.isConnecting = false;
            console.error("[freeq] re-auth failed:", reauthErr);
            this.settings.oauthSession = void 0;
            await this.saveSettings();
            new import_obsidian8.Notice("Re-authentication failed. Please log in again.");
            return;
          }
        } else {
          this.isConnecting = false;
          this.settings.oauthSession = void 0;
          await this.saveSettings();
          new import_obsidian8.Notice("Session expired. Please log in again.");
          return;
        }
      }
    } else if (oauthSession) {
      token = oauthSession.webToken;
      method = "web-token";
      effectiveDid = oauthSession.did;
    } else if (did && appPassword) {
      try {
        const session = await this.createPdsSession(did, appPassword, pdsUrl);
        if (!session) {
          this.isConnecting = false;
          new import_obsidian8.Notice("Failed to authenticate with PDS. Check your credentials.");
          return;
        }
        token = session.accessJwt;
        method = "pds-session";
      } catch (e) {
        this.isConnecting = false;
        console.error("[freeq] PDS auth error:", e);
        new import_obsidian8.Notice("PDS authentication failed.");
        return;
      }
    }
    const desiredNick = nick || oauthSession?.nick || did?.split(":").pop()?.slice(0, 15) || "guest";
    if (!token) {
      new import_obsidian8.Notice(
        "Connecting as guest \u2014 configure OAuth or App Password in settings to authenticate."
      );
    }
    if (this.registrationTimer) {
      clearTimeout(this.registrationTimer);
      this.registrationTimer = null;
    }
    this.client.addListener((ev) => {
      if (ev.type === "registered" && this.client.isConnected() && this.client.channels.size === 0) {
        this.isConnecting = false;
        if (this.registrationTimer) {
          clearTimeout(this.registrationTimer);
          this.registrationTimer = null;
        }
        const channels = (this.settings.autoJoinChannels || "#general").split(",").map((c) => c.trim()).filter(Boolean);
        for (const ch of channels) {
          this.client.join(ch);
        }
        if (channels.length && !this.client.activeChannel) {
          this.client.activeChannel = channels[0];
        }
      }
      if (ev.type === "state") {
        if (ev.state === "connected") {
          this.isConnecting = false;
          if (this.registrationTimer) clearTimeout(this.registrationTimer);
          this.registrationTimer = setTimeout(() => {
            if (!this.client.isConnected()) {
              console.log("[freeq] Registration timeout \u2014 001 never received");
              new import_obsidian8.Notice("Server connected but never sent registration confirmation. Try reconnecting.");
            }
          }, 15e3);
        } else if (ev.state === "disconnected") {
          this.isConnecting = false;
          if (this.registrationTimer) {
            clearTimeout(this.registrationTimer);
            this.registrationTimer = null;
          }
        }
      }
    });
    this.client.connect(serverUrl, desiredNick, token, effectiveDid, method);
    new import_obsidian8.Notice("Connecting to FreeQ\u2026");
  }
  disconnect() {
    this.isConnecting = false;
    if (this.registrationTimer) {
      clearTimeout(this.registrationTimer);
      this.registrationTimer = null;
    }
    this.client.disconnect();
    new import_obsidian8.Notice("Disconnected from FreeQ.");
  }
  // ── PDS Blob Upload ──
  async uploadNoteBlob() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian8.Notice("No active note.");
      return;
    }
    try {
      const result = await this.uploadBlobToPds(
        new Blob([await this.app.vault.read(file)], { type: "text/markdown" }),
        file.name
      );
      if (!result) return;
      await navigator.clipboard.writeText(result);
      new import_obsidian8.Notice(`Blob URL copied to clipboard`);
    } catch (e) {
      console.error("[freeq] blob upload failed:", e);
      new import_obsidian8.Notice(`Upload failed: ${e.message || String(e)}`);
    }
  }
  async uploadBlobToPds(blob, filename) {
    if (!this.client.isConnected()) {
      new import_obsidian8.Notice("Not connected to FreeQ server. Connect first.");
      return null;
    }
    const did = this.settings.oauthSession?.did || this.settings.did;
    if (!did) {
      new import_obsidian8.Notice("Not authenticated. Log in via OAuth first.");
      return null;
    }
    const wsUrl = this.settings.serverUrl;
    if (!wsUrl) {
      new import_obsidian8.Notice("FreeQ server URL not configured.");
      return null;
    }
    const serverUrl = wsUrl.replace(/^wss:\/\//, "https://").replace(/^ws:\/\//, "http://").replace(/\/irc$/, "");
    const content = new Uint8Array(await blob.arrayBuffer());
    const name = filename || "paste.png";
    const type = blob.type || "application/octet-stream";
    console.warn("[freeq] uploading blob", { filename: name, mimeType: type, did });
    try {
      const result = await uploadBlobViaFreeQ({ serverUrl, did, content, filename: name, mimeType: type });
      return result.url;
    } catch (err) {
      if (err instanceof BlobUploadError && err.status === 401) {
        console.warn("[freeq] upload 401 \u2014 reconnecting to refresh server PDS session");
        new import_obsidian8.Notice("Server session expired \u2014 reconnecting\u2026");
        try {
          this.client.disconnect();
          this.connect();
          await this.client.waitForRegistration();
          const retry = await uploadBlobViaFreeQ({ serverUrl, did, content, filename: name, mimeType: type });
          return retry.url;
        } catch (retryErr) {
          console.error("[freeq] upload retry after reconnect failed:", retryErr);
          new import_obsidian8.Notice("Upload failed after reconnect. Try again.");
          return null;
        }
      }
      if (err instanceof BlobUploadError) {
        const body = typeof err.body === "string" ? null : err.body;
        const stepUpUrl = body?.error === "step_up_required" ? body.step_up_url : null;
        if (stepUpUrl) {
          const resolvedStepUpUrl = this.resolveUrl(stepUpUrl, serverUrl);
          const stepUp = new URL(resolvedStepUpUrl);
          if (!stepUp.searchParams.has("did")) {
            stepUp.searchParams.set("did", did);
          }
          this.openExternalUrl(stepUp.toString());
          new import_obsidian8.Notice("Complete the upload approval in your browser, then paste again.");
          return null;
        }
      }
      throw err;
    }
  }
  resolveUrl(url, baseUrl) {
    try {
      return new URL(url, baseUrl).toString();
    } catch {
      return url;
    }
  }
  openExternalUrl(url) {
    const electron = window.require?.("electron");
    if (electron?.shell?.openExternal) {
      electron.shell.openExternal(url);
      return;
    }
    window.open(url, "_blank");
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_FREEQ);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf?.setViewState({ type: VIEW_TYPE_FREEQ, active: true });
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async openChatInPopout() {
    const { workspace } = this.app;
    const preferredChannel = this.client.activeChannel || this.settings.lastChannel;
    if (preferredChannel) {
      this.client.activeChannel = preferredChannel;
    }
    const leaf = workspace.openPopoutLeaf();
    await leaf.setViewState({ type: VIEW_TYPE_FREEQ, active: true });
    workspace.revealLeaf(leaf);
  }
  // ── Broker token refresh ──
  async refreshBrokerToken(brokerToken) {
    const brokerBody = JSON.stringify({ broker_token: brokerToken });
    const url = this.settings.brokerUrl.replace(/\/$/, "") + "/session";
    const res = await (0, import_obsidian8.requestUrl)({
      url,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: brokerBody
    });
    if (res.status >= 400) {
      if (res.status === 401) {
        this.settings.oauthSession = void 0;
        await this.saveSettings();
        throw new Error("Broker token expired. Please log in again.");
      }
      throw new Error(`Broker returned ${res.status}`);
    }
    return res.json;
  }
  // ── PDS Session (app-password fallback) ──
  async createPdsSession(didOrHandle, appPassword, pdsUrl) {
    let did = didOrHandle;
    if (!didOrHandle.startsWith("did:")) {
      const resolved = await this.resolveHandle(didOrHandle);
      if (!resolved) return null;
      did = resolved;
    }
    let endpoint = pdsUrl;
    if (!endpoint || endpoint === "https://bsky.social") {
      const doc = await this.fetchDidDocument(did);
      if (doc?.service?.[0]?.serviceEndpoint) {
        endpoint = doc.service[0].serviceEndpoint;
      }
    }
    const url = endpoint.replace(/\/$/, "") + "/xrpc/com.atproto.server.createSession";
    try {
      const resp = await (0, import_obsidian8.requestUrl)({
        url,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ identifier: did, password: appPassword })
      });
      if (resp.status >= 400) {
        console.error("[freeq] createSession failed:", resp.text);
        return null;
      }
      const data = resp.json;
      if (!data.accessJwt) return null;
      return { accessJwt: data.accessJwt };
    } catch (e) {
      console.error("[freeq] createSession network error:", e);
      return null;
    }
  }
  async resolveHandle(handle) {
    try {
      const resp = await (0, import_obsidian8.requestUrl)(
        `https://plc.directory/resolveHandle?handle=${encodeURIComponent(handle)}`
      );
      if (resp.status >= 400) return null;
      return resp.json?.did || null;
    } catch {
      return null;
    }
  }
  async fetchDidDocument(did) {
    try {
      const url = did.startsWith("did:plc:") ? `https://plc.directory/${did}` : did.startsWith("did:web:") ? `https://${did.slice(8)}/.well-known/did.json` : null;
      if (!url) return null;
      const resp = await (0, import_obsidian8.requestUrl)(url);
      if (resp.status >= 400) return null;
      return resp.json;
    } catch {
      return null;
    }
  }
};
